In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# X = [1, 2, 3, 4] <-> [x0, x1, x2, x3]
# y = [2] <-> w_init + w_0*x0 + ... + w_3*x3

# Fake X_data
X_data = np.random.random((10000, 2))

# Fake semple_weights
sample_weights = np.array([3, 4]).reshape(2, )

# Fake y_data
y_data = np.matmul(X_data, sample_weights)

In [3]:
X_data[0]

array([0.86770483, 0.38750705])

In [4]:
sample_weights

array([3, 4])

In [5]:
y_data[0]

4.153142698950441

In [6]:
# Approximation Y

y_data = np.add(y_data, np.random.uniform(-0.5, 0.5))

In [7]:
y_data[0]

4.203043635771294

In [8]:
y_data = y_data.reshape(len(y_data), 1)
y_data.shape

(10000, 1)

In [9]:
# Start !!!
X_data

array([[0.86770483, 0.38750705],
       [0.12190522, 0.79740462],
       [0.16314329, 0.19139023],
       ...,
       [0.09332644, 0.63329734],
       [0.54098693, 0.18971366],
       [0.86985542, 0.95158408]])

In [10]:
y_data

array([[4.20304364],
       [3.60523509],
       [1.30489172],
       ...,
       [2.86306961],
       [2.43171636],
       [6.4658035 ]])

In [11]:
# Training !!!
# Tam thoi bo qua tap Validation

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size=0.2, random_state=42)

In [13]:
X_train.shape

(8000, 2)

In [14]:
X_test.shape

(2000, 2)

In [15]:
n_dim = X_train.shape[1]
n_dim

2

In [16]:
# Placeholder for pass data
X = tf.placeholder(tf.float32, [None, n_dim])

y = tf.placeholder(tf.float32, [None, 1])

In [17]:
# Trainable weights
W = tf.Variable(tf.ones([n_dim, 1]))

b = tf.Variable(np.random.randn(), dtype=tf.float32)

In [18]:
pred = tf.add(tf.matmul(X, W), b)

In [19]:
loss = tf.reduce_mean(tf.square(pred - y))

In [20]:
learning_rate = 0.01

optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(loss)

In [21]:
init = tf.global_variables_initializer()

In [22]:
sess = tf.Session()

In [23]:
# Training

sess.run(init)

epochs = 5000

lost_history = []

for epoch in range(epochs):
    sess.run(optimizer, feed_dict={X: X_train, y: y_train})
    
    test_loss = sess.run(loss, feed_dict={X: X_test, y: y_test})
    
    lost_history.append(test_loss)
    if (epoch + 1) % 500 == 0:
        print("Epoch:", epoch + 1, "| Cost:", test_loss)

Epoch: 500 | Cost: 0.13001955
Epoch: 1000 | Cost: 0.042888213
Epoch: 1500 | Cost: 0.014290717
Epoch: 2000 | Cost: 0.004789228
Epoch: 2500 | Cost: 0.0016102013
Epoch: 3000 | Cost: 0.00054236053
Epoch: 3500 | Cost: 0.00018286503
Epoch: 4000 | Cost: 6.168815e-05
Epoch: 4500 | Cost: 2.081838e-05
Epoch: 5000 | Cost: 7.0281126e-06


In [24]:
# lost_history

In [25]:
sess.run(W)

array([[2.9937418],
       [3.9931664]], dtype=float32)

In [26]:
sess.run(b)

0.056813836

In [27]:
import matplotlib.pyplot as plt

plt.plot(lost_history[:])
plt.show()

<Figure size 640x480 with 1 Axes>

In [28]:
pred_y = sess.run(pred, feed_dict={X: [[2, 3]]})

In [29]:
print(pred_y)

[[18.023798]]
