In [2]:
import numpy as np

**Câu 1:** Thay thế tất cả các phần tử trong một mảng có giá trị lớn hơn 30 thành 30 và dưới 10 thành 10.

In [2]:
# input: [28. 15. 22. 42.  1.  7. 34. 41.  8. 29.]
# output: [28. 15. 22. 30. 10. 10. 30. 30. 10. 29.]

In [3]:
ex1 = np.array([28, 15, 22, 42,  1,  7, 34, 41,  8, 29], dtype=np.float64)

In [4]:
# Trả về những phần tử < 30; những phần tử > 30 thay bằng 30
ex1 = np.where(ex1 < 30, ex1, 30)

# Trả về những phần tử > 10; những phần tử < 10 thay bằng 10
ex1 = np.where(ex1 > 10, ex1, 10)
ex1

array([28., 15., 22., 30., 10., 10., 30., 30., 10., 29.])

**Câu 2:** Lấy vị trí của 3 giá trị lớn nhất trong một mảng numpy

Readmore: https://docs.scipy.org/doc/numpy/reference/generated/numpy.argpartition.html

In [5]:
# input: [28. 15. 22. 42.  1.  7. 34. 41.  8. 29.]
# output: [6 7 3]

In [6]:
ex2 = np.array([28, 15, 22, 42,  1,  7, 34, 41,  8, 29], dtype=np.float64)

# Sử dụng `np.argpartition` 
np.argpartition(ex2, -3)[-3:]

array([6, 3, 7])

**Câu 3:** Chuyển một mảng nhiều chiều thành một mảng 1 chiều

In [7]:
# input: [array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
# output: [0 1 2 3 4 5 6 7 8 9]

In [8]:
ex3 = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [7, 8, 9]
])

ex3.flatten()

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

**Câu 4:** Tạo one-hot encoding cho một mảng numpy. One-hot encoding nhằm chuyển đổi mỗi giá trị (số nguyên) n thành một vector v mà vị trí thứ n trong vector v mang giá trị 1 và  tất cả vị trí khác đều mang giá trị 0.

In [9]:
# input: [2 1 3 3 1 2]
# output: array([[0., 1., 0.],
#               [1., 0., 0.],
#               [0., 0., 1.],
#               [0., 0., 1.],
#               [1., 0., 0.],
#               [0., 1., 0.]])

In [7]:
ex4 = np.array([2, 1, 3, 3, 1, 2])
index = ex4 - 1
get_max_value = np.max(ex4)

result = np.zeros((ex4.shape[0], get_max_value))

In [8]:
result[np.arange(index.shape[0]), index] = 1
print(result)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


**Câu 5:** Sắp xếp các phần tử trong một mảng 1 chiều

In [12]:
# input: [3 6 4 8]
# output: [3 4 6 8]

In [13]:
ex5 = np.array([3, 6, 4, 8])
np.sort(ex5)

array([3, 4, 6, 8])

**Câu 6:** Tìm giá trị lớn nhất trong mỗi hàng và mỗi cột của một mảng 2d

In [14]:
# input
# [[5 1 7]
#  [3 5 2]
#  [6 4 5]]
 
# output
# Max by column
# [6 5 7]
# Max by row
# [7 5 6]

In [15]:
ex6 = np.array([
    [5, 1, 7],
    [3, 5, 2],
    [6, 4, 5]
])

In [16]:
# Max by column
np.ndarray.max(ex6, axis=0)

array([6, 5, 7])

In [17]:
# Max by row
np.ndarray.max(ex6, axis=1)

array([7, 5, 6])

**Câu 7:** Tìm các phần tử trùng lặp (lần xuất hiện thứ 2 trở đi) trong mảng đã cho
và đánh dấu chúng là True. Lần đầu tiên xuất hiện là False.

In [18]:
# [0 3 3 1 2 0 2 0]
# [False False  True False False  True  True  True]

In [50]:
ex7 = np.array([0, 3, 3, 1, 2, 0, 2, 0])

z = np.unique(ex7)

ex7_2 = np.ones((ex7.shape[0]), dtype=bool)

# Xuất hiện lần đầu -> False 
for i in range(ex7.shape[0]):
    if ex7[i] in z:
        index = np.argwhere(z == ex7[i])
        ex7_2[i] = False
        z = np.delete(z, index)
        
print(ex7_2)

[False False  True False False  True  True  True]


**Câu 8:** Trừ theo dòng mảng 2 chiều arr2d bằng mảng 1 chiều arr1d



In [20]:
# arr2d
# [[3 3 3]
#  [4 4 4]
#  [5 5 5]]
# arr1d
# [1 1 1]
# output
# [[2 2 2]
#  [3 3 3]
#  [4 4 4]]

In [21]:
arr2d = np.array([
    [3, 3, 3],
    [4, 4, 4],
    [5, 5, 5]
])

arr1d = np.array([1, 1, 1])

In [22]:
arr2d - arr1d

array([[2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

**Câu 9:** Bỏ tất cả các giá trị nan từ một mảng numpy

Readmore: https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.isfinite.html

In [23]:
#  input: [1.  2.  3. nan  5.  6.  7. nan]
# output: [1., 2., 3., 5., 6., 7.]

In [24]:
from numpy import nan
ex9 = np.array([1, 2, 3, nan, 5, 6, 7, nan], dtype=np.float64)
ex9

array([ 1.,  2.,  3., nan,  5.,  6.,  7., nan])

In [25]:
ex9[np.isfinite(ex9)]

array([1., 2., 3., 5., 6., 7.])

**Câu 10:** Lấy tất cả vị trí nơi các phần tử có giá trị khác nhau

In [26]:
# input
# arr1: [3 4 5 6 7 8]
# arr2: [3 3 6 6 7 7]
# output
# [1, 2, 5]

In [27]:
arr1 = np.array([3, 4, 5, 6, 7, 8])
arr2 = np.array([3, 3, 6, 6, 7, 7])

np.where(arr1 != arr2)[0]

array([1, 2, 5])