In [1]:
import tensorflow as tf

In [2]:
# in tensorflow version
tf.__version__

'1.14.0'

## Introduction about Tensorflow

### Constant
- Đại lượng không thay đổi trong quá trình chạy chương trình 

In [6]:
x1 = tf.constant(1, name='const_x1')
print(x1)

Tensor("const_x1:0", shape=(), dtype=int32)


In [10]:
x2 = tf.constant(2.0)
print(x2)

Tensor("Const_5:0", shape=(), dtype=float32)


In [13]:
x3 = tf.constant(3, dtype='float32')
print(x3)

Tensor("Const_7:0", shape=(), dtype=float32)


In [15]:
v1 = tf.constant([1, 2, 3], dtype=tf.float32, name='v1_const_vector')
print(v1)

Tensor("v1_const_vector_1:0", shape=(3,), dtype=float32)


In [16]:
sess = tf.Session()

In [21]:
sess.run(x1)

1

In [22]:
sess.run(v1)

array([1., 2., 3.], dtype=float32)

**Note**: tensor có thể là một số thực, số nguyên, chuỗi, matrix 1D,2D,3D... mutil-dimention

In [23]:
# Create tensor 2D
v2 = tf.constant([
    [1, 2, 3],
    [3, 4, 5]
], dtype=tf.float32, name='2d_matrix')

In [24]:
print(v2)

Tensor("2d_matrix:0", shape=(2, 3), dtype=float32)


In [25]:
sess.run(v2)

array([[1., 2., 3.],
       [3., 4., 5.]], dtype=float32)

In [26]:
v2.eval(session=sess)

array([[1., 2., 3.],
       [3., 4., 5.]], dtype=float32)

### Perform operators

In [31]:
# Add x1 + x2

# y1 = x1 + x2 (Fail - x1, x2 not same dtype)

y1 = x2 + x3

print(y1)

Tensor("add_3:0", shape=(), dtype=float32)


**Note**: khi xử lý trên tensor thì phải cùng `dtype`

In [32]:
sess.run(y1)

5.0

In [33]:
v3 = tf.constant([
    [3, 4, 5],
    [5, 6, 7]
], dtype=tf.float32, name='2d_matrix2')

In [34]:
y2 = v2 + v3

In [35]:
sess.run(y2)

array([[ 4.,  6.,  8.],
       [ 8., 10., 12.]], dtype=float32)

## Placeholder

### Create
- Placeholder sử dụng trong trường hợp chúng ta cần load dữ liệu vào.

In [36]:
p1 = tf.placeholder(dtype=tf.float32)
p2 = tf.placeholder(dtype=tf.float32)

In [37]:
# Asign operation for placeholder

o_add = p1 + p2
o_mul = p1 * p2
o_delta = p1**2 + p2**2

In [38]:
print(o_add)

Tensor("add_5:0", dtype=float32)


### Feed value for placeholder

In [39]:
d_value = {
    p1 : 20,
    p2 : 10
}

sess.run(o_add, feed_dict=d_value)

30.0

In [40]:
sess.run(o_delta, feed_dict=d_value)

500.0

In [41]:
sess.run([o_add, o_mul, o_delta], feed_dict=d_value)

[30.0, 200.0, 500.0]

## Variables

### Create

In [47]:
var_1 = tf.Variable(name='var_1', initial_value=10)
var_2 = tf.Variable(name='var_2', initial_value=50)

**Note**: cần phải khởi tạo biến trước khi đưa vào session và tính toán trên session 

In [48]:
sess.run(var_1.initializer)

In [49]:
sess.run(var_1)

10

In [52]:
# Khởi tạo toàn bộ 
tf.global_variables_initializer().run(session=sess)

In [53]:
sess.run(var_2)

50