**Câu 1:** Đọc tập dữ liệu Iris dùng hàm `np.genfromtxt()` với `dtype='object'`.  Dữ liệu trả về là một mảng 2 chiều, với các phần tử có kiểu là byte.

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Cach 1: Nhap du lieu su dung thu vien pandas

dataFrame = pd.read_csv('iris.csv', header=None)
print(dataFrame.shape)

(30, 5)


In [3]:
# Cach 2: doc du lieu su dung ham np.genfromtxt()

iris = np.genfromtxt('iris.csv', delimiter=',', dtype='object')
print(iris.shape)

(30, 5)


In [4]:
# Lay mot dong du lieu:
a_row = iris[0]
print(a_row)

[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']


In [5]:
# In kieu du lieu cho phan tu
print(a_row[0], type(a_row[0]))
print(a_row[1], type(a_row[1]))
print(a_row[2], type(a_row[2]))
print(a_row[3], type(a_row[3]))
print(a_row[4], type(a_row[4]))

b'5.1' <class 'bytes'>
b'3.5' <class 'bytes'>
b'1.4' <class 'bytes'>
b'0.2' <class 'bytes'>
b'Iris-setosa' <class 'bytes'>


**Câu 3:**  Tạo một mảng 2 chiểu gồm 4 cột dữ liệu đầu tiên.

In [6]:
x = dataFrame.values[:, 0:4]
# print(x)
print(x.shape)

(30, 4)


In [7]:
# In 4 dong dau
print(x[0:4, :])

[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


**Câu 4:**  Tìm giá trị trung bình (`mean`), trung vị (`median`), độ lệch chuẩn (`standard deviation`) của cột sepal_length của tập dữ liệu iris (cột thứ 1).

In [8]:
first_col = dataFrame.values[:, 0].reshape(-1, 1)
print(first_col.shape)

(30, 1)


In [9]:
mean = np.mean(first_col)
print(mean)

5.843333333333333


In [10]:
median = np.median(first_col)
print(median)

5.75


In [11]:
std = np.std(first_col)
print(std)

0.947868954843208


**Câu 5:**  Chuẩn hóa (`normalize`) cột sepallength để giá trị nằm trong khoảng từ 0 đến 1.

Công thức chuẩn hoá:

`(norm_array_a = a(i) - min.a) / (max.a - min.a)`

In [12]:
norm_first_col = (first_col - first_col.min()) / first_col.ptp()
print(norm_first_col[:5])

[[0.21874999999999983]
 [0.15625000000000003]
 [0.09374999999999996]
 [0.06249999999999979]
 [0.18749999999999992]]


**Câu 6:**  Tính `softmax` cho cột sepallength.

Công thức:

![Image](https://wikimedia.org/api/rest_v1/media/math/render/svg/11b61d999176b3e8db6efe6632b7cc62fa4d4c53)

In [13]:
def softmax(x):
    e_x = np.exp(x*1.0 - np.max(x))
    return e_x / e_x.sum()

In [14]:
# in chi 4 so sau phan thap phan
np.set_printoptions(precision=4)

first_col = np.float64(first_col)
print(softmax(first_col))

[[0.0103]
 [0.0084]
 [0.0069]
 [0.0063]
 [0.0093]
 [0.0139]
 [0.0063]
 [0.0093]
 [0.0051]
 [0.0084]
 [0.069 ]
 [0.0379]
 [0.0624]
 [0.0154]
 [0.0418]
 [0.0188]
 [0.0343]
 [0.0084]
 [0.0462]
 [0.0114]
 [0.0343]
 [0.0208]
 [0.0762]
 [0.0343]
 [0.0418]
 [0.1257]
 [0.0084]
 [0.0931]
 [0.0511]
 [0.0843]]


**Câu 8:**  Đọc 4 cột dữ liệu đầu tiên, và lọc các dòng có petallength (cột thứ 3) > 1.5 và sepallength (cột thứ 1) < 5.0.

In [15]:
iris_2d = np.genfromtxt('iris.csv', delimiter=',', dtype='float', usecols=[0,1,2,3])

print(iris_2d.shape)
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)

out = iris_2d[condition]
print(out)

(30, 4)
[[4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [16]:
# Cách 2
print(x.shape)
x = np.float64(x)
condition2 = (x[:, 2] > 1.5) & (x[:, 0] < 5.0)

out2 = x[condition]
print(out2)

(30, 4)
[[4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


**Câu 9:**  Tìm mối tương quan giữa SepalLength (cột thứ 1) và PetalLength (cột thứ 3).

Đọc hiểu: https://docs.scipy.org/doc/numpy/reference/generated/numpy.corrcoef.html

In [17]:
out_corr = np.corrcoef(x[:, 0], x[:, 2])
print(out_corr)

[[1.     0.8766]
 [0.8766 1.    ]]


**Câu 10:**  Tìm các giá trị duy nhất và số lượng các giá trị duy nhất trong cột species.

In [18]:
out = np.unique(dataFrame.values[:, 4], return_counts=True)
print(out)

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object), array([10, 10, 10]))


**Câu 11:**  Chuyển đổi cột 3 petallength thành mảng như sau:

Nhỏ hơn 3   –>   `small`

Từ 3->5     –>   `medium`

Lớn hơn 5   –>   `large`

In [19]:
col_3 = dataFrame.values[:,2]
print(col_3)

[1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 4.7 4.5 4.9 4.0 4.6 4.5 4.7 3.3
 4.6 3.9 6.0 5.1 5.9 5.6 5.8 6.6 4.5 6.3 5.8 6.1]


In [20]:
# Hàm np.digitize: trả về vị trí chỉ số của bin mà mỗi phần tử thuộc khoảng bin tương ứng
# chuyển đổi mảng sang mảng bin tương ứng với bảng định nghĩa chuyển đổi 

bin_pental_length = np.digitize(iris[:,2].astype(float),[0,3,5,10])
print(bin_pental_length)

[1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 2 3 3 3]


In [21]:
# ánh xạ bảng bin thành văn bản tương ứng 
label_map = {1:'small', 2:'medium', 3:'large', 4:np.nan}
map_bin_petallength = [label_map[x] for x in bin_pental_length]
print(map_bin_petallength)

['small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'large', 'large', 'large', 'large', 'large', 'medium', 'large', 'large', 'large']


**Câu 12:**  Tạo một cột mới, trong đó giá trị mỗi phần tử là:

`(petallength + sepal_length) / 2`

In [22]:
sepal_length = dataFrame.values[:,0]
petal_length = dataFrame.values[:,2]
new_col = (petal_length + sepal_length) / 2

print(new_col)

[3.25 3.1500000000000004 3.0 3.05 3.2 3.5500000000000003 3.0 3.25
 2.9000000000000004 3.2 5.85 5.45 5.9 4.75 5.55 5.1 5.5 4.1 5.6 4.55 6.15
 5.449999999999999 6.5 5.949999999999999 6.15 7.1 4.7 6.8 6.25 6.65]


In [23]:
# Định dạng cột mới cùng số chiều với iris_2d
print(new_col.shape)
new_col = new_col[:, np.newaxis]

print(new_col.shape)

(30,)
(30, 1)


In [24]:
# Thêm cột mới vào dataFarme dùng hàm hstack
out = np.hstack([dataFrame, new_col])
print(out.shape)

(30, 6)


In [25]:
print(out)

[[5.1 3.5 1.4 0.2 'Iris-setosa' 3.25]
 [4.9 3.0 1.4 0.2 'Iris-setosa' 3.1500000000000004]
 [4.7 3.2 1.3 0.2 'Iris-setosa' 3.0]
 [4.6 3.1 1.5 0.2 'Iris-setosa' 3.05]
 [5.0 3.6 1.4 0.2 'Iris-setosa' 3.2]
 [5.4 3.9 1.7 0.4 'Iris-setosa' 3.5500000000000003]
 [4.6 3.4 1.4 0.3 'Iris-setosa' 3.0]
 [5.0 3.4 1.5 0.2 'Iris-setosa' 3.25]
 [4.4 2.9 1.4 0.2 'Iris-setosa' 2.9000000000000004]
 [4.9 3.1 1.5 0.1 'Iris-setosa' 3.2]
 [7.0 3.2 4.7 1.4 'Iris-versicolor' 5.85]
 [6.4 3.2 4.5 1.5 'Iris-versicolor' 5.45]
 [6.9 3.1 4.9 1.5 'Iris-versicolor' 5.9]
 [5.5 2.3 4.0 1.3 'Iris-versicolor' 4.75]
 [6.5 2.8 4.6 1.5 'Iris-versicolor' 5.55]
 [5.7 2.8 4.5 1.3 'Iris-versicolor' 5.1]
 [6.3 3.3 4.7 1.6 'Iris-versicolor' 5.5]
 [4.9 2.4 3.3 1.0 'Iris-versicolor' 4.1]
 [6.6 2.9 4.6 1.3 'Iris-versicolor' 5.6]
 [5.2 2.7 3.9 1.4 'Iris-versicolor' 4.55]
 [6.3 3.3 6.0 2.5 'Iris-virginica' 6.15]
 [5.8 2.7 5.1 1.9 'Iris-virginica' 5.449999999999999]
 [7.1 3.0 5.9 2.1 'Iris-virginica' 6.5]
 [6.3 2.9 5.6 1.8 'Iris-virginic

**Câu 13:**  Lấy mẫu ngẫu nhiên cột `species` của mảng iris sao cho số lượng chọn `setose` gấp đôi số lượng của `versicolor` và `virginica`.

In [26]:
species = dataFrame.values[:,4]

label = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])

out1 = np.random.choice(label, 30, p=[0.5, 0.25, 0.25])
print(np.unique(out1, return_counts=True))

# Chú ý: với số mẫu của data nhỏ nên độ lệch lớn. Với data lớn hơn sẽ chính xác hơn 


(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='<U15'), array([15, 12,  3]))


**Câu 14:**  Tìm giá trị lớn thứ hai của petallength trong nhóm `setosa`

In [27]:
x = dataFrame.values[:, 0:5]
# print(x)
setosa = x[x[:, 4] == 'Iris-setosa']
print(setosa)

[[5.1 3.5 1.4 0.2 'Iris-setosa']
 [4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']
 [5.4 3.9 1.7 0.4 'Iris-setosa']
 [4.6 3.4 1.4 0.3 'Iris-setosa']
 [5.0 3.4 1.5 0.2 'Iris-setosa']
 [4.4 2.9 1.4 0.2 'Iris-setosa']
 [4.9 3.1 1.5 0.1 'Iris-setosa']]


In [28]:
# chỉ lấy cột 2 và chuyển thành kiểu float
petal_length_setosa = setosa[:,2].astype(float)

# Lấy giá trị lớn thứ hai của mảng 
out = np.unique(np.sort(petal_length_setosa))[-2]
print(out)

1.5


**Câu 15:**  Sắp xếp tập dữ liệu iris dựa trên cột `sepallength`

In [29]:
# Sắp xếp cột 0 (SepalLangth)
out = x[x[:, 0].argsort()]
print(out)

[[4.4 2.9 1.4 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [4.6 3.4 1.4 0.3 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.9 2.5 4.5 1.7 'Iris-virginica']
 [4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.9 2.4 3.3 1.0 'Iris-versicolor']
 [4.9 3.1 1.5 0.1 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']
 [5.0 3.4 1.5 0.2 'Iris-setosa']
 [5.1 3.5 1.4 0.2 'Iris-setosa']
 [5.2 2.7 3.9 1.4 'Iris-versicolor']
 [5.4 3.9 1.7 0.4 'Iris-setosa']
 [5.5 2.3 4.0 1.3 'Iris-versicolor']
 [5.7 2.8 4.5 1.3 'Iris-versicolor']
 [5.8 2.7 5.1 1.9 'Iris-virginica']
 [6.3 2.9 5.6 1.8 'Iris-virginica']
 [6.3 3.3 4.7 1.6 'Iris-versicolor']
 [6.3 3.3 6.0 2.5 'Iris-virginica']
 [6.4 3.2 4.5 1.5 'Iris-versicolor']
 [6.5 3.0 5.8 2.2 'Iris-virginica']
 [6.5 2.8 4.6 1.5 'Iris-versicolor']
 [6.6 2.9 4.6 1.3 'Iris-versicolor']
 [6.7 2.5 5.8 1.8 'Iris-virginica']
 [6.9 3.1 4.9 1.5 'Iris-versicolor']
 [7.0 3.2 4.7 1.4 'Iris-versicolor']
 [7.1 3.0 5.9 2.1 'Iris-virginica']
 [7.2 3.6 6.1 2.5 'Iris-virginica']
 [7.3 2.9 6.

**Câu 16:**  Tìm giá trị xuất hiện nhiều nhất trong cột petallength (cột thứ 3) trong tập dữ liệu iris. Lấy các phần tử duy nhất và số lượng mỗi phần tử.

In [30]:
values, counts = np.unique(x[:,2], return_counts=True)
print(values)

[1.3 1.4 1.5 1.7 3.3 3.9 4.0 4.5 4.6 4.7 4.9 5.1 5.6 5.8 5.9 6.0 6.1 6.3
 6.6]


In [31]:
print(counts)

[1 5 3 1 1 1 1 3 2 2 1 1 1 2 1 1 1 1 1]


**Câu 17:**  Tìm vị trí xuất hiện đầu tiên của một giá trị lớn hơn 1.0 trong cột thứ 4 (petalwidth) của tập dữ liệu iris.

In [32]:
petalwidth = x[:,3].astype('float') > 1.0

# Hàm argwhere lấy index của mảng thoả mãn điều kiện cho trước 
index = np.argwhere(petalwidth)[0]
print(index)

[10]


**Câu 18:** Tạo id nhóm dựa trên một biến phân loại cho trước, dùng cột species từ mảng iris.

In [33]:
output1 = [np.argwhere(np.unique(species) == s).tolist()[0][0] 
           for val in np.unique(species) 
           for s in species[species==val]]

In [34]:
print(output1)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
