Cho mảng một chiều có giá trị từ 0 đến 9, chuyển mảng 1 chiều này thành mảng 2 chiều có 2 hàng (dòng).

In [1]:
import numpy as np

arr = np.arange(10)
print(arr.shape)

arr.reshape(2, 5)

(10,)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [2]:
arr2 = np.arange(10)

# -1 có ý nghĩa là số cột của arr_2d được tính tự động 
arr_2d = arr2.reshape(2, -1)

print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]
