Cho hai mảng sau:

`arr1 = np.arange(10).reshape(2,-1)`

`arr2 = np.arange(10,0,-1).reshape(2,-1)`

hãy xếp chồng 2 mảng theo chiều dọc 

In [1]:
import numpy as np

arr1 = np.arange(10).reshape(2,-1)
arr2 = np.arange(10,0,-1).reshape(2,-1)

print(arr1)
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10  9  8  7  6]
 [ 5  4  3  2  1]]


In [2]:
arr = np.concatenate((arr1, arr2), axis = 0)
print(arr)
print(arr.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
(4, 5)


In [3]:
# Cách 2
print(np.vstack([arr1, arr2]))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [4]:
# Cách 2
print(np.r_[arr1, arr2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
