Cho hai mảng sau:

`arr1 = np.array([1, 2, 3, 4, 5])`

`arr2 = np.array([3, 4, 5, 6, 7])`

lấy phần tử chung của 2 mảng `arr1` và `arr2`.

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])

print(arr1)
print(arr2)

[1 2 3 4 5]
[3 4 5 6 7]


In [2]:
np.intersect1d(arr1, arr2)

array([3, 4, 5])