Cho mảng sau

`arr = np.arange(12).reshape(4, 3)`

Hoán đổi cột 1 và 2 trong mảng arr.

In [1]:
import numpy as np

arr =np.arange(12).reshape(4, -1)
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [2]:
out = arr[(1, 0, 2), :]
print(out)

[[3 4 5]
 [0 1 2]
 [6 7 8]]
