In mảng 2 chiều kiểu `float` chỉ với 2 số sau phần thập phân 

In [1]:
import numpy as np

rand_arr = np.random.random([2, 3])
print(rand_arr)

[[0.33772369 0.26188607 0.56425843]
 [0.0787847  0.61708338 0.75573146]]


In [2]:
np.set_printoptions(precision=2)
print(rand_arr)

[[0.34 0.26 0.56]
 [0.08 0.62 0.76]]
