## Thuật toán Summed-area Table 

Tính tổng các thành phần của 1 ma trận hình chữ nhật một cách nhanh chóng và hiệu quả.

Ví dụ: Tính tổng các số trong khung hình chữ nhật `màu tím`
![image](https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Integral_image_application_example.svg/340px-Integral_image_application_example.svg.png)

Kết quả:
![image.png](https://upload.wikimedia.org/wikipedia/commons/5/58/Summed_area_table.png)

Xây dựng thuật toán Summed-area Table cơ bản:

### 1. Xây dựng bằng matrix 

In [1]:
# Ma trận ban đầu & bảng Sum 

import numpy as np

height, width = 10, 10

# build sum-area table for each disparity
data = np.random.randint(1, 10, (height, width))
memory = np.ones((height, width))

# first item
memory[0, 0] = data[0, 0]

# first row
# Voi x: truc hoanh, y: truc tung
for y in range(1):
    for x in range(1, width):
        # the first: memory[0, 1] = memory[0, 0] + data[0, 1]
        memory[y, x] = memory[y, x - 1] + data[y, x]

# first column
for x in range(1):
    for y in range(1, height):
        memory[y, x] = memory[y - 1, x] + data[y, x]

for y in range(1, height):
    for x in range(1, width):
        # memory[1, 1] = memory[1, 0] + memory[0, 1] - memory[0, 0] + data[1, 1]
        memory[y, x] = memory[y, x - 1] + memory[y - 1, x] - memory[y - 1, x - 1] + data[y, x]

print(data)
print(memory)

[[8 4 1 7 2 5 8 5 8 2]
 [5 4 5 6 1 2 2 3 7 7]
 [7 5 9 3 3 4 4 6 6 5]
 [8 9 9 5 5 6 4 8 4 8]
 [9 4 1 2 7 8 2 1 7 9]
 [6 8 6 1 3 5 4 2 6 6]
 [7 9 8 4 8 9 9 1 9 9]
 [4 2 6 9 3 9 9 1 4 5]
 [3 3 4 1 1 2 4 2 4 4]
 [5 9 3 4 1 5 5 9 8 5]]
[[  8.  12.  13.  20.  22.  27.  35.  40.  48.  50.]
 [ 13.  21.  27.  40.  43.  50.  60.  68.  83.  92.]
 [ 20.  33.  48.  64.  70.  81.  95. 109. 130. 144.]
 [ 28.  50.  74.  95. 106. 123. 141. 163. 188. 210.]
 [ 37.  63.  88. 111. 129. 154. 174. 197. 229. 260.]
 [ 43.  77. 108. 132. 153. 183. 207. 232. 270. 307.]
 [ 50.  93. 132. 160. 189. 228. 261. 287. 334. 380.]
 [ 54.  99. 144. 181. 213. 261. 303. 330. 381. 432.]
 [ 57. 105. 154. 192. 225. 275. 321. 350. 405. 460.]
 [ 62. 119. 171. 213. 247. 302. 353. 391. 454. 514.]]


Tính giá trị trong miền `màu tím`:

![image.png](https://imgur.com/VOknuM1.png)

In [2]:
kernel_half = 1
x, y = 5, 5
x0 = x - kernel_half  # x0 = 4
x1 = x + kernel_half  # x0 = 6
y0 = y - kernel_half  # y0 = 4
y1 = y + kernel_half  # y0 = 6

a = memory[y0 - 1, x0 - 1]  # memory[3, 3]
b = memory[y1, x0 - 1]  # memory[6, 3]
c = memory[y0 - 1, x1]  # memory[3, 6]
d = memory[y1, x1]  # memory[6, 6]
ssd = d - b - c + a
print('Result:', ssd)

Result: 55.0


### 2. Xây dựng bằng Numpy 
- Đọc thêm về thư viện numpy.cumsum [Tại đây](https://github.com/thanhhff/AIVietnam_Basic/blob/master/Python%20Doc/02.%20Th%C6%B0%20vi%E1%BB%87n%20Numpy/numpy.cumsum.ipynb)

In [3]:
memory_np = data.cumsum(axis=0).cumsum(axis=1)
print(memory_np)

[[  8  12  13  20  22  27  35  40  48  50]
 [ 13  21  27  40  43  50  60  68  83  92]
 [ 20  33  48  64  70  81  95 109 130 144]
 [ 28  50  74  95 106 123 141 163 188 210]
 [ 37  63  88 111 129 154 174 197 229 260]
 [ 43  77 108 132 153 183 207 232 270 307]
 [ 50  93 132 160 189 228 261 287 334 380]
 [ 54  99 144 181 213 261 303 330 381 432]
 [ 57 105 154 192 225 275 321 350 405 460]
 [ 62 119 171 213 247 302 353 391 454 514]]


Tính kết quả trên `memory_np`:

In [4]:
kernel_half = 1
x, y = 5, 5
x0 = x - kernel_half  # x0 = 4
x1 = x + kernel_half  # x0 = 6
y0 = y - kernel_half  # y0 = 4
y1 = y + kernel_half  # y0 = 6

a = memory[y0 - 1, x0 - 1]  # memory[3, 3]
b = memory[y1, x0 - 1]  # memory[6, 3]
c = memory[y0 - 1, x1]  # memory[3, 6]
d = memory[y1, x1]  # memory[6, 6]
ssd = d - b - c + a
print('Result:', ssd)

Result: 55.0
