### Hàm numpy.cumsum

`numpy.cumsum(a, axis=None, dtype=None, out=None)`

Hàm này trả về tổng tích luỹ các phần tử dọc theo trục (axis) đã cho !

In [1]:
import numpy as np
a = np.array([[1,3,5],[2,4,6]])

In [2]:
a

array([[1, 3, 5],
       [2, 4, 6]])

In [3]:
np.cumsum(a)

array([ 1,  4,  9, 11, 15, 21])

In [4]:
# Chỉ định type của đầu ra 
np.cumsum(a, dtype = float)

array([ 1.,  4.,  9., 11., 15., 21.])

In [5]:
# Tính tổng tích luỹ theo chiều dọc
np.cumsum(a , axis = 0)

array([[ 1,  3,  5],
       [ 3,  7, 11]])

In [6]:
# Tính tổng tích luỹ theo chiều ngang 
np.cumsum(a, axis = 1)

array([[ 1,  4,  9],
       [ 2,  6, 12]])